version = 0.1

[default] 

[default.deploy]

[default.deploy.parameters]
stack_name = "{{ cookiecutter.stack_name }}"
s3_bucket = "aws-sam-stacks"
s3_prefix = "{{ cookiecutter.stack_name }}"
region = "us-east-1"

confirm_changeset = true

capabilities = [
    "CAPABILITY_IAM",
]    

image_repositories = []

parameter_overrides = []
