SKU_PATTERN = r'^[a-zA-Z0-9][a-zA-Z0-9-_]*[a-zA-Z0-9]$'
SLUG_PATTERN = r'^[a-zA-Z0-9][a-zA-Z0-9-]*[a-zA-Z0-9]$'
UUID4_PATTERN = r'[a-z0-9-]{36}'
USERNAME_PATTERN = r'^\d+$'
POSTAL_CODE_PATTERN = r'^\d{5}$'
TOKEN_URLSAFE_PATTERN = r'^[a-zA-Z0-9_-]+$'
FULL_ISOFORMAT_PATTERN = r'\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}\.\d{6}([+-]\d{2}:\d{2})'
SPANISH_LETTERS_PATTERN = r'^[A-Za-zñÑáéíóúÁÉÍÓÚ ]+$'
COGNITO_ACCESS_TOKEN_PATTERN = r'^[A-Za-z0-9-_=.]+$'
